version: "3.8"

services:
  app:
    container_name: video-watermark-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      PORT: 3000
      UPLOAD_DIR: uploads
    command: ["npm", "start"]
